# Generated by Django 4.2.14 on 2024-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_customuser_first_name_hash_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name_uz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
